
name: Terraform Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7
      - name: Terraform Init
        working-directory: terraform/
        run: terraform init -backend=false
      - name: Terraform Validate
        working-directory: terraform/
        run: terraform validate
